services:
  db: # projet-docker-kubernetes-db-1
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
  pgadmin: # projet-docker-kubernetes-pgadmin-1
    image: dpage/pgadmin4:9.3
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: louandeshayes@gmail.com
      PGADMIN_DEFAULT_PASSWORD: LouanPgAdmin
  web:
    image: node:20
    restart: always
    working_dir: /app
    ports:
      - "8080:5000"
    command: sh -c "npm install && npm start"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      PGADMIN_URL: http://pgadmin:8888
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
      - pgadmin
# logins | MDP de la DTB :
#    louandeshayes@gmail.com | LouanPgAdmin
#    no mathisborger24@gmail.com | mathis
#    no bodinv@3il.fr | veronique
#    no jabirn@3il.fr | jabirn

# Build conteneur DTB : docker compose -f Docker_compose.yaml up -d
# Save DTB : docker exec -t projet-docker-kubernetes-db-1 pg_dumpall -c -U postgres > backend/db/dump_DTB.sql
# Restore DTB : cat backend/db/dump_DTB.sql | docker exec -i projet-docker-kubernetes-db-1 psql -U postgres
