services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
  pgadmin:
    image: dpage/pgadmin4:9.3
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: louandeshayes@gmail.com
      PGADMIN_DEFAULT_PASSWORD: LouanPgAdmin

# logins | MDP de la DTB :
#    louandeshayes@gmail.com | LouanPgAdmin
#    mathisborger24@gmail.com | mathis
#    bodinv@3il.fr | veronique
#    jabirn@3il.fr | jabirn

# Build conteneur DTB : docker compose -f DTBcompose.yaml up
# Save DTB : docker exec -t (id_du_conteneur_postgres) pg_dumpall -c -U postgres > dump_DTB.sql
# Restore DTB : cat dump_DTB.sql | docker exec -i (id_du_conteneur_postgres) psql -U postgres