# Déploiement de la Base de données MySQL
apiVersion: v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_DATABASE
              value: db-todo-list
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}

---
# Déploiement de l'application Todo List
apiVersion: v1
kind: Deployment
metadata:
  name: app-todo-list
spec:
  selector:
    matchLabels:
      app: app-todo-list
  replicas: 1
  template:
    metadata:
      labels:
        app: app-todo-list
    spec:
      containers:
        - name: app-todo-list
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: db-todo-list
            - name: MYSQL_DATABASE
              value: db-todo-list
            - name: DB_USER
              value: root
            - name: DB_PASS
              value: rootpassword
